name: Flutter Lint

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [main, feat/*]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            **/pubspec.lock
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19"
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze --fatal-infos